### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Pandapip1** [mlc-ai/mlc-llm#36] opened 2023-05-01 21:42 UTC
Pretty self-explanatory: can we get an Android version of this?

**Comment by durmazt** [comment] 2023-05-02 15:31
upcoming [https://github.com/mlc-ai/mlc-llm/issues/15](see also)

**Comment by shiqimei** [comment] 2023-05-08 13:11
duplicate of #4 , the team is working in progress for the android port.

**Comment by junrushao** [comment] 2023-05-09 03:43
It’s up! https://twitter.com/bohanhou1998/status/1655772690760994818

**Comment by Pandapip1** [comment] 2023-05-09 10:49
> duplicate of #4

Have no idea how I missed that. Closing.

**Closed** 2023-05-09 10:49 UTC
Labels: feature request
