### ISSUE TITLE
[Bug]  Prepare_libs.sh for iOS fails

### ISSUE THREAD

**Issue by llSourcell** [mlc-ai/mlc-llm#810] opened 2023-08-25 22:19 UTC
## 🐛 Bug

i have followed all the steps to load MLC Chat via source for iOS but when running ./prepare_libs.sh  i get this error saying the 'core' crate not is not found. any ideas what could be wrong? i did run "rustup target add aarch64-apple-ios`" and its installed. it seems to be an issue with the rust toolchain... 

``` bash
[ 72%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/source_utils.cc.o
[ 72%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/static_library.cc.o
[ 72%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/system_library.cc.o
[ 72%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/thread_pool.cc.o
[ 72%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/threading_backend.cc.o
[ 81%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/vm/bytecode.cc.o
[ 81%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/vm/executable.cc.o
[ 81%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/vm/memory_manager.cc.o
[ 81%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/vm/vm.cc.o
[ 81%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/workspace_pool.cc.o
[ 81%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/metal/metal_device_api.mm.o
[ 81%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/metal/metal_module.mm.o
[ 81%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/contrib/random/random.cc.o
[ 90%] Building CXX object tvm/CMakeFiles/tvm_runtime_objs.dir/src/runtime/contrib/sort/sort.cc.o
[ 90%] Built target tvm_runtime_objs
[ 90%] Linking CXX static library libtvm_runtime.a
You have build static version of the TVM runtime library. Make sure to use --whole-archive when linking it into your project.
[ 90%] Built target tvm_runtime
[ 90%] Generating aarch64-apple-ios/release/libtokenizers_c.a
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling libc v0.2.147
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling crossbeam-utils v0.8.16
   Compiling memchr v2.5.0
   Compiling syn v1.0.109
   Compiling fnv v1.0.7
   Compiling ident_case v1.0.1
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-ios` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-ios`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
make[3]: *** [tokenizers/aarch64-apple-ios/release/libtokenizers_c.a] Error 101
make[2]: *** [tokenizers/CMakeFiles/tokenizers_c.dir/all] Error 2
make[1]: *** [CMakeFiles/mlc_llm_static.dir/rule] Error 2
make: *** [mlc_llm_static] Error 2

```

## To Reproduce

1.
1.
1.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA):
 - Operating system (e.g. Ubuntu/Windows/MacOS/...):
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...)
 - How you installed MLC-LLM (`conda`, source):
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10):
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 - Any other relevant information:

**Comment by Hzfengsy** [comment] 2023-08-26 02:49
That usually happens when `rustup` and `rust` are not installed from the same source (e.g. one from HomeBrew but the other does not). Check via `which rustup` and `which rust`

**Comment by tqchen** [comment] 2023-08-29 00:21
closing for now, as likely the issue is what @Hzfengsy mentioned

**Closed** 2023-08-29 00:21 UTC
Labels: bug

**Comment by FelipeLujan** [comment] 2023-12-02 17:14
can confirm.

uninstalling rust from brew with `brew uninstall rust  `
and then installing rustup with the command here https://www.rust-lang.org/tools/install fixe the issue for me
