### ISSUE TITLE
[ANDROID][Feature Request] Add a small delay before prompt processing

### ISSUE THREAD

**Issue by qnixsynapse** [mlc-ai/mlc-llm#993] opened 2023-09-28 05:03 UTC
## 🚀 Feature
Kindly consider introducing a brief delay(few miliseconds) before inputting the prompt into the model for prompt processing. Currently, when the enter key is pressed on the on-screen keyboard, the prompt is immediately sent to the model. However, this abrupt transition clashes with the keyboard's closing 'animation,' leading to a less than ideal user experience.

Incorporating a delay to allow the on-screen keyboard to complete its closing animation before initiating prompt processing will greatly enhance the overall user experience.

**Comment by GameOverFlowChart** [comment] 2023-10-01 08:16
I don't think that that's the correct way of fixing this problem. I think the the whole ai runs on the main thread which is bad praxis. Only gui should run on the main thread. That way the keyboard could disappear without the calculation of the ai preventing it.

**Comment by akarshanbiswas** [comment] 2023-10-01 14:27
@GameOverFlowChart That is a correct assessment too.

**Comment by cyx-6** [comment] 2023-10-01 20:27
Thanks for your suggestion, @akarshanbiswas! But @GameOverFlowChart is right, we never introduce any artificial delay in main thread or UI thread in Andorid development. And I am kind of confused about abrupting transition clashes with the keyboard's closing 'animation'. Do you have a short gif to show how that happens and we may have other solution if possible.

**Comment by junrushao** [comment] 2023-10-01 20:40
To be clear, at the moment, MLC LLM runs LLM in a different thread on GPU, which is not UI/main thread, so to clarify, are you suggesting sleeping for a few seconds in MLC's thread before loading things onto GPU?

**Comment by akarshanbiswas** [comment] 2023-10-02 02:27
I am sharing a gif for everyone to understand. 

![ezgif-4-0dcf3f3055.gif](https://github.com/mlc-ai/mlc-llm/assets/17230826/4a84c04b-a00b-4840-8fd0-bb837b540637)



This is actually the current behaviour.

**Comment by cyx-6** [comment] 2023-10-02 04:10
Thanks for sharing. Do you mean the overlap of virtual keyboard and the chat input box, after clicking the send button? I notice that there is a frame with this case. 

But I am not sure if this is caused by system itself. Because we only use the default system UI interfaces, without any animation design manually.

**Comment by akarshanbiswas** [comment] 2023-10-02 05:12
@cyx-6 Have you noticed the short freeze when sent button is touched? I am talking about that.

**Comment by cyx-6** [comment] 2023-10-02 07:17
@akarshanbiswas like this?
![image](https://github.com/mlc-ai/mlc-llm/assets/16838183/3c1303df-da2b-4138-b6cb-e9374029501f)

**Comment by akarshanbiswas** [comment] 2023-10-02 07:18
Yes. The animation got effected because the UI froze.

**Comment by cyx-6** [comment] 2023-10-02 07:21
emmm, I see. I have no concrete idea how it comes and how to solve it perfectly. BTW, what is your phone model and system info? I can take a look and try to fix it later.

**Comment by GameOverFlowChart** [comment] 2023-10-02 12:41
> I have no concrete idea how it comes

I can add that the lagg is stronger if the model size is bigger + the input text is longer. If I would have to guess it's the step that converts the text into tokens that blocks the gui thread. My phone seems to struggle much more while reading the input, once the model starts outputting tokens the phone is very responsive. I don't know if this is mlc specific or if the first step is in general more computation heavy.

**Closed** 2024-05-11 02:08 UTC
Labels: feature request
