### ISSUE TITLE
[Bug] error: package org.apache.tvm does not exist when building app in Android Studio

### ISSUE THREAD

**Issue by NSTiwari** [mlc-ai/mlc-llm#1839] opened 2024-02-26 13:55 UTC
## 🐛 Bug

When building the app in Android Studio, I get the following error:
D:\mlc-llm\android\library\src\main\java\ai\mlc\mlcllm\ChatModule.java:3: error: package org.apache.tvm does not exist
import org.apache.tvm.Device;

![image](https://github.com/mlc-ai/mlc-llm/assets/37960279/2037707c-f812-42a6-9986-58cb4cd56f96)

It turns out this is due to the following files not getting generated in the build/outputs folder when the file `prepare_libs.sh` is executed.

./build/output/arm64-v8a/libtvm4j_runtime_packed.so
./build/output/tvm4j_core.jar

I've followed the documentation, however, when I run the `prepare_libs.sh` file, I get the following error:
![image](https://github.com/mlc-ai/mlc-llm/assets/37960279/415e0450-7a64-43ad-bc70-a3076243080e)

I've never worked with CMAKE before. I'm just following the [documentation](https://llm.mlc.ai/docs/deploy/android) step-by-step.
What is possibly going wrong? Or what do I need to do to get the jar files generated?

## To Reproduce

1. Cloned the mlc-llm repository in D: drive.
2. Installed Rust, CMake, TVM, Android NDK.
3. Set the system variables ANDROID_NDK, TVM_NDK_CC
4. Download the Gemma 2b-it model and copied the gemma-2b-it-q4f16_1-android.tar file to the project directory - `D:\mlc-llm\dist\prebuilt_libs\gemma-2b-it`
5. Executed the `prepare_libs.sh` file.
6. Got the error below:

## Expected behavior

I'm expecting the `prepare_libs.sh` script to execute successfully in order to generate the following files:
./build/output/arm64-v8a/libtvm4j_runtime_packed.so
./build/output/tvm4j_core.jar

Without these files, the app in Android Studio doesn't build and throws the error below:
![image](https://github.com/mlc-ai/mlc-llm/assets/37960279/019c86c8-6672-4996-a4c1-cf9cd1a2e9d9)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Windows 10
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): OnePlus Nord CE 3 Lite 5G
 - How you installed MLC-LLM (`conda`, source): Yes
 - How you installed TVM-Unity (`pip`, source): Yes
 - Python version (e.g. 3.10): 3.10.5
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):
 
![image](https://github.com/mlc-ai/mlc-llm/assets/37960279/fb022c29-aefe-4dc8-a984-67567c274ce2)

 - Any other relevant information:

**Comment by NSTiwari** [comment] 2024-02-26 14:04
@Kartik14: I'd appreciate your assistance here.

**Comment by Kartik14** [comment] 2024-02-26 16:28
It seems like your libraries are not built correctly. Can you share your output when you run the `prepare_libs.sh` script?

**Comment by NSTiwari** [comment] 2024-02-27 11:49
> It seems like your libraries are not built correctly. Can you share your output when you run the `prepare_libs.sh` script?

```
sh prepare_libs.sh
+ rustup target add aarch64-linux-android
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
+ mkdir -p build/model_lib
+ py prepare_model_lib.py
Creating lib from ['D:\\mlc-llm\\dist\\prebuilt_libs/gemma-2b-it/gemma-2b-it-q4f16_1-android.tar']..
+ cd build
+ touch config.cmake
+ '[' 0 -ne 0 ']'
+ cmake .. -DCMAKE_BUILD_TYPE=Release '-DCMAKE_TOOLCHAIN_FILE=C:\Users\tiwar\AppData\Local\Android\Sdk\ndk\26.2.11394342/build/cmake/android.toolchain.cmake' -DCMAKE_INSTALL_PREFIX=. -DCMAKE_CXX_FLAGS=-O3 -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=android-24 -DANDROID_PLATFORM=android-24 -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ON -DANDROID_STL=c++_static -DUSE_HEXAGON_SDK=OFF -DMLC_LLM_INSTALL_STATIC_LIB=ON -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DUSE_OPENCL=ON -DUSE_CUSTOM_LOGGING=ON
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

    MSBuild version 17.9.5+33de0b227 for .NET Framework
    Build started 27-02-2024 17:17:58.

    Project "D:\mlc-llm\android\library\build\CMakeFiles\3.29.0-rc2\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(839,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\mlc-llm\android\library\build\CMakeFiles\3.29.0-rc2\VCTargetsPath.vcxproj]
    Done Building Project "D:\mlc-llm\android\library\build\CMakeFiles\3.29.0-rc2\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "D:\mlc-llm\android\library\build\CMakeFiles\3.29.0-rc2\VCTargetsPath.vcxproj" (default target) (1) ->
    (_CheckForInvalidConfigurationAndPlatform target) ->
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(839,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\mlc-llm\android\library\build\CMakeFiles\3.29.0-rc2\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.34


  Exit code: 1

-- Configuring incomplete, errors occurred!

```

**Comment by NSTiwari** [comment] 2024-02-28 04:26
@Kartik14: Could you please help? I'm using Windows 10. Do I need to change something in `prepare_list.sh`?

**Comment by Kartik14** [comment] 2024-02-28 05:58
I am not really sure what the issue is. I don't have a windows machine to reproduce this.

**Comment by Ammar-Ishfaq** [comment] 2024-03-08 05:43
I'm also getting this in Windows 11, could anyone possibly figure out the solution for it?

**Comment by tqchen** [comment] 2024-05-11 02:48
closing for now, please checkout the latest https://llm.mlc.ai/docs/deploy/android.html

**Closed by tqchen** 2024-05-11 02:48 UTC
Labels: bug
