### ISSUE TITLE
[Bug] Decoding not stopping even after stop token is generated

### ISSUE THREAD

**Issue by ayubSubhaniya** [mlc-ai/mlc-llm#1315] opened 2023-11-22 07:36 UTC
## 🐛 Bug

I am using a mistral model with MLC optimizations. Default stop token in mistral is `</s>`, but I am seeing weird behaviour that  very frequent model is not stopping decoding even after stop token is generated.

## To Reproduce

Code that I am using for generate
```
from mlc_chat import ChatModule

  self.model = ChatModule(
      model=os.path.join(export_path, "params"),
      lib_path=os.path.join(export_path, "lib.so"),
      model_lib_path=os.path.join(export_path, "lib.so"),
  )
  with open(
      os.path.join(export_path, "params", "mlc-chat-config.json")
  ) as config:
      self.chat_config = self.chat_config._from_json(json.load(config))

decoded_output = self.model.generate(prompt=model_input)
```
## Expected behavior

Input Prompt
```
<|system|> You are customer care bot </s>
<|assistant|> How can I assist you </s>
<|user|> I want to change mobile number  </s>
<|assistant|>
```

Output That I got
```
You can visit our mobile store </s>
<|user|> Thank you  </s>
<|assistant|> Welcome  </s>
```

Expected output
`You can visit our mobile store </s>`

**Comment by ayubSubhaniya** [comment] 2023-11-22 07:39
I want to what is default behaviour of MLC chat module? Does it consider output score of generated stop token as well to decide if generation should be stopped or not?

**Comment by ayubSubhaniya** [comment] 2023-11-22 08:39
This is conversation template that I am using
```
{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}
```

**Comment by ayubSubhaniya** [comment] 2023-11-22 08:40
I am actually applying chat template beforehand, and then sending just a prompt to MLC chat module

> Curious which model and conversation template are you using?
> 
> For context, a conversation template is defined in [`mlc-chat-config.json`](https://huggingface.co/mlc-ai/mlc-chat-Llama-2-70b-chat-hf-q4f16_1/blob/main/mlc-chat-config.json#L4) and used to control the patterns of token stopping. For llama2 chat models, the default template is "llama-2", and the base model uses "LM" (short for "language model").

**Comment by varshith15** [comment] 2023-11-22 09:49
@junrushao there are a few issues, 

1. The LM conv_template doesn't have `conv.stop_str` functionality
2. Also, the `conv.stop_tokens` isn't working as excepted

fixing the above ^

**Comment by varshith15** [comment] 2023-11-22 09:54
@junrushao also [`cm.reset()`](            self.reset_chat()) shouldn't be part of `cm.generate`. It's causing issues pertaining the it being chat completion vs normal generate. https://github.com/mlc-ai/mlc-llm/pull/1107#issuecomment-1816611490

**Comment by varshith15** [comment] 2023-11-22 17:10
The issue seems to be difference in tokenization, the hf tokenizer and the mlc tokenizer are giving different outputs for the same texts.
Debugging this further
cc: @CharlieFRuan

**Comment by jetro30087** [comment] 2023-11-28 00:16
I think I found the problem.
llm_chat.cc   

I changed line 1143 from this:

 stop_triggered_ =
        std::any_of(this->conversation_.stop_tokens.begin(), this->conversation_.stop_tokens.end(),
                    [next_token](int32_t token) { return token == next_token; });

to this:

int32_t stop_token = 0;  

 stop_triggered_ =
        std::any_of(this->conversation_.stop_tokens.begin(), this->conversation_.stop_tokens.end(),
                    [next_token](int32_t token) { return token == next_token; || next_token = **_stop_token_** });

Where stop token equals the int representing the **_stop token_**, for example MLChat's stop token equals "32000".

I think sometimes the return token only contains part of the stop string, so it's not recognized, somewhere later in the code, the stop string does return the full vector and it's removed from subsequent strings, so stop triggered never gets called in subsequent decodes. That's my best guess, but I'm not encountering the problem after doing this.

**Comment by CharlieFRuan** [comment] 2023-11-28 01:58
Really appreciate the inputs @varshith15 @jetro30087! Spent some time looking into this today, I think the issue is that [MLC's reading of all the token files](https://github.com/mlc-ai/mlc-llm/blob/9e2854085558f2d324f38c0449b740ea1e27031a/cpp/tokenizers.cc) (`tokenizer.json`, `tokenizer.model`, etc.) does not have parity with [how huggingface handles it](https://github.com/huggingface/transformers/blob/v4.35.2/src/transformers/models/auto/tokenization_auto.py#L590).

It is not just mistral (how we are using `tokenizer.model` instead of `tokenizer.json`), but also models like Open Hermes, where we did not take into account `tokenizer_config.json` and hence missing some stop tokens when decoding.

@davidpissarra and I will keep looking into this tomorrow and try to fix this.

**Comment by CharlieFRuan** [comment] 2023-12-04 16:37
Closing this issue for now; feel free to open another one if there are further issues. Thanks!

**Closed by CharlieFRuan** 2023-12-04 16:37 UTC
Labels: bug
