### ISSUE TITLE
could you tell me to support Chinese dialogue? 

### ISSUE THREAD

**Issue by leoring123** [mlc-ai/mlc-llm#100] opened 2023-05-07 13:20 UTC
Excuse me, could you tell me to support Chinese dialogue? Please advice on how to make the model supports Chinese dialogue, use are either in English or in the code.

**Comment by shiqimei** [comment] 2023-05-08 10:10
duplicate of #77

**Comment by junrushao** [comment] 2023-05-08 23:05
Hey thanks for asking! MLC LLM doesn't limit which language to use per se, but good language support really depends on what underlying model it is generating code for. For example, the MOSS model @yzh119 is working should support Chinese a bit better than Vicuna if I read correctly.

**Closed** 2023-06-14 04:46 UTC
Labels: question
