### ISSUE TITLE
[Bug] MACOS M1 webgpu build undefined symbols 

### ISSUE THREAD

**Issue by DavidGOrtega** [mlc-ai/mlc-llm#1628] opened 2024-01-18 20:16 UTC
## 🐛 Bug

related to #452 ?
Im following [the guide](https://llm.mlc.ai/docs/install/emcc.html#install-web-build) however I have undefined symbols.

```sh
./scripts/prep_emcc_deps.sh

...
warning: undefined symbol: TVMWasmPackedCFunc (referenced by top-level compiled C/C++ code)
warning: undefined symbol: TVMWasmPackedCFuncFinalizer (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZN3tvm7runtime9threading10NumThreadsEv (referenced by top-level compiled C/C++ code)
warning: undefined symbol: _ZN3tvm7runtime9threading15ResetThreadPoolEv (referenced by top-level compiled C/C++ code)
emcc: warning: warnings in JS library compilation [-Wjs-compiler]
python3 emcc/decorate_as_wasi.py dist/wasm/tvmjs_runtime.js dist/wasm/tvmjs_runtime.wasi.js cjs
python3 emcc/decorate_as_wasi.py dist/wasm/tvmjs_runtime.js src/tvmjs_runtime_wasi.js es
```

When I then try to load the model I have this error:

```
[FATAL] /Users/davidgortega/Documents/projects/mlc/mlc-llm/3rdparty/tvm/src/runtime/relax_vm/vm.cc:676: InternalError: Check failed: (func.defined()) is false: Error: Cannot find PackedFunc vm.builtin.paged_attention_kv_cache_attention in either Relax VM kernel library, or in TVM runtime PackedFunc registry, or in global Relax functions of the VM executable
```

## To Reproduce

Just follow [the guide](https://llm.mlc.ai/docs/install/emcc.html#install-web-build)

## Environment

 - Platform WebGPU
 - Operating system  MACOS Ventura 13.6.1
 - Device  MacBook Pro M1
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): pip
 - Python version (e.g. 3.10): 3.9
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models): 3party/tvm
 
any idea @tqchen?

**Comment by MasterJH5574** [comment] 2024-03-04 23:03
Given mlc-ai/web-llm#293 has been merged, likely the issue is addressed. So gonna close this issue for now. You are welcome to create a new one if the issue persists or there's any other issue.

**Closed by MasterJH5574** 2024-03-04 23:03 UTC
Labels: bug
