### ISSUE TITLE
[Question] while use the command python3 prepare_libs.py, there same error ocured

### ISSUE THREAD

**Issue by tombang** [mlc-ai/mlc-llm#2639] opened 2024-07-09 13:13 UTC
## ❓ General Questions

(venv_llama) tangben@tb:~/MLCNEW/mlc-llm/android/mlc4j$ python3 prepare_libs.py 
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
[2024-07-09 21:09:33] INFO prepare_libs.py:91: Entering "/home/tangben/MLCNEW/mlc-llm/android/mlc4j/build" for MLC LLM and tvm4j build.
[2024-07-09 21:09:33] INFO prepare_libs.py:95: Set TVM_SOURCE_DIR to "/home/tangben/MLCNEW/mlc-llm/3rdparty/tvm"
[2024-07-09 21:09:33] INFO prepare_libs.py:23: Running cmake
-- Hide private symbols
-- TVM_SOURCE_DIR: /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm
-- Hide private symbols...
-- Forbidding undefined symbols in shared library, using -Wl,--no-undefined on platform Android
-- Building for Android
-- Didn't find the path to CCACHE, disabling ccache
-- VTA build with VTA_HW_PATH=/home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/3rdparty/vta-hw
-- Build VTA runtime with target: sim
-- Enabled runtime search for OpenCL library location
-- Couldn't build OpenCL-Gtests
-- Android Vulkan_INCLUDE_DIRS=/home/tangben/Android/Sdk/ndk/25.2.9519653/sources/third_party/vulkan/src/include
-- Skip finding SPIRV in Android, make sure you only build tvm runtime.
-- Build with contrib.random
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Git found: /usr/bin/git
-- Found TVM_GIT_COMMIT_HASH=f5f048bbd71513f087799f987019e3931f68a6d9
-- Found TVM_GIT_COMMIT_TIME=2024-06-03 09:18:53 -0400
-- Building with TVM Map...
-- Build with thread support...
-- CLANG_VERSION 14.0
-- Setting enhanced clang warning flags
-- Added "-fuse-ld=lld" to linker flags -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments 
-- Build without FlashInfer
-- system-nameAndroid
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- VERSION: 0.2.00
CMake Warning at /home/tangben/MLCNEW/mlc-llm/CMakeLists.txt:107 (message):
  Cannot find libflash_attn.  The model must not have been built with
  --use-flash-attn-mqa option.

-- TVM_SOURCE_DIR: /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm
-- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
-- Try to find jni directly from android env
-- JNI_INCLUDE_DIRS=/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tangben/MLCNEW/mlc-llm/android/mlc4j/build
[2024-07-09 21:09:34] INFO prepare_libs.py:55: Running cmake build
Consolidate compiler generated dependencies of target tvm_libinfo_objs
Consolidate compiler generated dependencies of target tokenizer_cpp_objs
[  0%] Built target tokenizers_c
[  6%] Built target tvm4j_core
[  6%] Building CXX object mlc_llm/tvm/CMakeFiles/tvm_libinfo_objs.dir/src/support/libinfo.cc.o
[  6%] Built target tokenizer_cpp_objs
Consolidate compiler generated dependencies of target sentencepiece-static
Consolidate compiler generated dependencies of target mlc_llm_objs
Consolidate compiler generated dependencies of target tvm_runtime_objs
[ 37%] Built target sentencepiece-static
[ 37%] Built target tokenizers_cpp
[ 62%] Built target mlc_llm_objs
[100%] Built target tvm_runtime_objs
[100%] Built target tvm_libinfo_objs
[100%] Linking CXX static library libtvm_runtime.a
You have build static version of the TVM runtime library. Make sure to use --whole-archive when linking it into your project.
[100%] Built target tvm_runtime
[100%] Built target mlc_llm_static
Consolidate compiler generated dependencies of target tvm4j_runtime_packed
gmake[3]: *** No rule to make target 'lib/libmodel_android.a', needed by 'libtvm4j_runtime_packed.so'.  Stop.
gmake[3]: *** Waiting for unfinished jobs....
[100%] Building CXX object CMakeFiles/tvm4j_runtime_packed.dir/home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc.o
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/ndarray.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/optional.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/./base.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/memory.h:26:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/object.h:574:67: error: no template named 'is_base_of_v' in namespace 'std'; did you mean 'is_base_of'?
  template <typename ObjectType, typename = std::enable_if_t<std::is_base_of_v<Object, ObjectType>>>
                                                             ~~~~~^~~~~~~~~~~~
                                                                  is_base_of
/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/type_traits:1725:29: note: 'is_base_of' declared here
struct _LIBCPP_TEMPLATE_VIS is_base_of
                            ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/ndarray.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/optional.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/./base.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/memory.h:26:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/object.h:574:62: error: template argument for non-type template parameter must be an expression
  template <typename ObjectType, typename = std::enable_if_t<std::is_base_of_v<Object, ObjectType>>>
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/type_traits:542:16: note: template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/ndarray.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/optional.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/./base.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/memory.h:26:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/object.h:595:46: error: no template named 'is_base_of_v' in namespace 'std'; did you mean 'is_base_of'?
            typename = std::enable_if_t<std::is_base_of_v<ObjectRef, ObjectRefType>>>
                                        ~~~~~^~~~~~~~~~~~
                                             is_base_of
/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/type_traits:1725:29: note: 'is_base_of' declared here
struct _LIBCPP_TEMPLATE_VIS is_base_of
                            ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/ndarray.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/optional.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/./base.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/memory.h:26:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/object.h:595:41: error: template argument for non-type template parameter must be an expression
            typename = std::enable_if_t<std::is_base_of_v<ObjectRef, ObjectRefType>>>
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/type_traits:542:16: note: template parameter is declared here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
               ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/ndarray.h:30:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/string.h:511:27: error: no matching member function for call to 'as'
  if (const auto* str = a.as<StringObj>()) {
                        ~~^~~~~~~~~~~~~
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/object.h:906:37: note: candidate template ignored: couldn't infer template argument ''
inline const ObjectType* ObjectRef::as() const {
                                    ^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/optional.h:157:43: note: candidate template ignored: couldn't infer template argument ''
inline Optional<ObjectRefType> ObjectRef::as() const {
                                          ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/ndarray.h:30:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/string.h:521:29: error: no matching member function for call to 'as'
  if (const auto* str_a = a.as<StringObj>()) {
                          ~~^~~~~~~~~~~~~
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/object.h:906:37: note: candidate template ignored: couldn't infer template argument ''
inline const ObjectType* ObjectRef::as() const {
                                    ^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/optional.h:157:43: note: candidate template ignored: couldn't infer template argument ''
inline Optional<ObjectRefType> ObjectRef::as() const {
                                          ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:28:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/ndarray.h:30:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/string.h:522:31: error: no matching member function for call to 'as'
    if (const auto* str_b = b.as<StringObj>()) {
                            ~~^~~~~~~~~~~~~
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/object.h:906:37: note: candidate template ignored: couldn't infer template argument ''
inline const ObjectType* ObjectRef::as() const {
                                    ^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/optional.h:157:43: note: candidate template ignored: couldn't infer template argument ''
inline Optional<ObjectRefType> ObjectRef::as() const {
                                          ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/packed_func.h:28:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:261:12: error: no template named 'bool_constant' in namespace 'std'; did you mean '_BoolConstant'?
    : std::bool_constant<std::is_base_of_v<
      ~~~~~^~~~~~~~~~~~~
           _BoolConstant
/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/type_traits:459:1: note: '_BoolConstant' declared here
using _BoolConstant _LIBCPP_NODEBUG_TYPE = integral_constant<bool, _Val>;
^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/packed_func.h:28:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:261:31: error: no template named 'is_base_of_v' in namespace 'std'; did you mean 'is_base_of'?
    : std::bool_constant<std::is_base_of_v<
                         ~~~~~^~~~~~~~~~~~
                              is_base_of
/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/type_traits:1725:29: note: 'is_base_of' declared here
struct _LIBCPP_TEMPLATE_VIS is_base_of
                            ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/packed_func.h:28:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:261:26: error: template argument for non-type template parameter must be an expression
    : std::bool_constant<std::is_base_of_v<
                         ^~~~~~~~~~~~~~~~~~
/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/type_traits:458:16: note: template parameter is declared here
template <bool _Val>
               ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/packed_func.h:28:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:268:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
inline constexpr bool is_valid_iterator_v = is_valid_iterator<T, IterType>::value;
^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:650:43: error: no template named 'invoke_result_t' in namespace 'std'
  template <typename F, typename U = std::invoke_result_t<F, T>>
                                     ~~~~~^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:661:58: error: no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
  template <typename F, typename = std::enable_if_t<std::is_same_v<T, std::invoke_result_t<F, T>>>>
                                                    ~~~~~^~~~~~~~~
                                                         is_same
/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/type_traits:550:29: note: 'is_same' declared here
struct _LIBCPP_TEMPLATE_VIS is_same : _BoolConstant<__is_same(_Tp, _Up)> { };
                            ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/packed_func.h:28:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:661:76: error: no member named 'invoke_result_t' in namespace 'std'
  template <typename F, typename = std::enable_if_t<std::is_same_v<T, std::invoke_result_t<F, T>>>>
                                                                      ~~~~~^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:661:92: error: 'F' does not refer to a value
  template <typename F, typename = std::enable_if_t<std::is_same_v<T, std::invoke_result_t<F, T>>>>
                                                                                           ^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:661:22: note: declared here
  template <typename F, typename = std::enable_if_t<std::is_same_v<T, std::invoke_result_t<F, T>>>>
                     ^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:661:99: error: expected member name or ';' after declaration specifiers
  template <typename F, typename = std::enable_if_t<std::is_same_v<T, std::invoke_result_t<F, T>>>>
                                                                                                  ^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:784:43: error: no template named 'invoke_result_t' in namespace 'std'
  template <typename F, typename U = std::invoke_result_t<F, T>>
                                     ~~~~~^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:792:47: error: no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
    constexpr bool is_same_output_type = std::is_same_v<T, U>;
                                         ~~~~~^~~~~~~~~
                                              is_same
/home/tangben/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/type_traits:550:29: note: 'is_same' declared here
struct _LIBCPP_TEMPLATE_VIS is_same : _BoolConstant<__is_same(_Tp, _Up)> { };
                            ^
In file included from /home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc:25:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/src/cpp/tvm_runtime.h:9:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/src/runtime/c_runtime_api.cc:27:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/device_api.h:29:
In file included from /home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/packed_func.h:28:
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:792:62: error: expected '(' for function-style cast or type construction
    constexpr bool is_same_output_type = std::is_same_v<T, U>;
                                         ~~~~~~~~~~~~~~~~~~~~^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:794:8: warning: constexpr if is a C++17 extension [-Wc++17-extensions]
    if constexpr (is_same_output_type) {
       ^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:794:19: error: constexpr if condition is not a constant expression
    if constexpr (is_same_output_type) {
                  ^~~~~~~~~~~~~~~~~~~
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:794:19: note: initializer of 'is_same_output_type' is unknown
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:792:20: note: declared here
    constexpr bool is_same_output_type = std::is_same_v<T, U>;
                   ^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:814:8: warning: constexpr if is a C++17 extension [-Wc++17-extensions]
    if constexpr (compatible_types) {
       ^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:876:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
inline constexpr bool is_tvm_array = false;
^
/home/tangben/MLCNEW/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/container/array.h:879:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
inline constexpr bool is_tvm_array<Array<T>> = true;
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
5 warnings and 20 errors generated.
gmake[3]: *** [CMakeFiles/tvm4j_runtime_packed.dir/build.make:76: CMakeFiles/tvm4j_runtime_packed.dir/home/tangben/MLCNEW/mlc-llm/3rdparty/tvm/jvm/native/src/main/native/org_apache_tvm_native_c_api.cc.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:263: CMakeFiles/tvm4j_runtime_packed.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:270: CMakeFiles/tvm4j_runtime_packed.dir/rule] Error 2
gmake: *** [Makefile:203: tvm4j_runtime_packed] Error 2
Traceback (most recent call last):
  File "/home/tangben/MLCNEW/mlc-llm/android/mlc4j/prepare_libs.py", line 120, in <module>
    main(parsed.mlc_llm_source_dir)
  File "/home/tangben/MLCNEW/mlc-llm/android/mlc4j/prepare_libs.py", line 103, in main
    run_cmake_build()
  File "/home/tangben/MLCNEW/mlc-llm/android/mlc4j/prepare_libs.py", line 66, in run_cmake_build
    subprocess.run(cmd, check=True, env=os.environ)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'tvm4j_runtime_packed', '--config', 'release', '-j12']' returned non-zero exit status 2.

**Comment by YiyanZhai** [comment] 2024-07-14 20:40
Duplicate of #2640

**Comment by tqchen** [comment] 2024-07-16 15:05
This file should not be directly invoked. Please follow official Android sdk docs and use mlc_LLM package instead https://llm.mlc.ai/docs/deploy/android.html please use the latest ndk

**Closed by tqchen** 2024-07-16 15:05 UTC
Labels: question
