### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Teiwazik** [mlc-ai/mlc-llm#2869] opened 2024-08-31 18:25 UTC
## 🐛 Bug

Phi 3.5 mini crashes mobile app

## Expected behavior

Phi 3.5 mini saying Initialize and then crashes the mobile app

## Environment

 - Platform: Android
 - Operating system: Android 14 (ColorOS 14)
 - Device: Realme GT Neo 2
 - How you installed MLC-LLM (`conda`, source): Last Android apk release
 - How you installed TVM-Unity (`pip`, source): ?
 - Python version (e.g. 3.10): latest idk
 - GPU driver version (if applicable): Snapdragon 870 GPU
 - CUDA/cuDNN: don't have
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):

**Comment by MasterJH5574** [comment] 2024-10-15 03:25
Hi, would you like to try out the latest app at https://github.com/mlc-ai/binary-mlc-llm-libs/releases/download/Android/mlc-chat.apk? Given the issue is a bit outdated I'm going to close it. Please feel free to open a new issue if the problem persists. Thank you!

**Closed by MasterJH5574** 2024-10-15 03:25 UTC
Labels: bug
