### ISSUE TITLE
[Bug] Android load model crash. org.apache.tvm.Base$TVMError: InternalError: Check failed: type_code_ == kTVMObjectHandle (0 vs. 8) : expected Object but got int

### ISSUE THREAD

**Issue by ccyina** [mlc-ai/mlc-llm#2777] opened 2024-08-08 08:25 UTC
## 🐛 Bug

Android Apk load llm crash, org.apache.tvm.Base$TVMError: InternalError: Check failed: type_code_ == kTVMObjectHandle (0 vs. 8) : expected Object but got int
## To Reproduce

1.build mlc llm use mac
2.follow [android sdk doc](https://llm.mlc.ai/docs/deploy/android.html), build model lib and android apk
3.run apk on android device. it will crash when click chat button to initialize

08-08 14:44:55.609 15833 15868 E AndroidRuntime: FATAL EXCEPTION: Thread-7
08-08 14:44:55.609 15833 15868 E AndroidRuntime: Process: ai.mlc.mlcchat, PID: 15833
08-08 14:44:55.609 15833 15868 E AndroidRuntime: org.apache.tvm.Base$TVMError: InternalError: Check failed: type_code_ == kTVMObjectHandle (0 vs. 8) : expected Object but got int
08-08 14:44:55.609 15833 15868 E AndroidRuntime: Stack trace:
08-08 14:44:55.609 15833 15868 E AndroidRuntime:   File "/Users/banma-1509/Develop/LLM/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/packed_func.h", line 2322
08-08 14:44:55.609 15833 15868 E AndroidRuntime:
08-08 14:44:55.609 15833 15868 E AndroidRuntime: 	at org.apache.tvm.Base.checkCall(Base.java:174)
08-08 14:44:55.609 15833 15868 E AndroidRuntime: 	at org.apache.tvm.Function.invoke(Function.java:132)
08-08 14:44:55.609 15833 15868 E AndroidRuntime: 	at ai.mlc.mlcllm.JSONFFIEngine.runBackgroundLoop(JSONFFIEngine.java:64)
08-08 14:44:55.609 15833 15868 E AndroidRuntime: 	at ai.mlc.mlcllm.MLCEngine$backgroundWorker$1.invoke(MLCEngine.kt:42)
08-08 14:44:55.609 15833 15868 E AndroidRuntime: 	at ai.mlc.mlcllm.MLCEngine$backgroundWorker$1.invoke(MLCEngine.kt:40)
08-08 14:44:55.609 15833 15868 E AndroidRuntime: 	at ai.mlc.mlcllm.BackgroundWorker$start$1.invoke(MLCEngine.kt:19)
08-08 14:44:55.609 15833 15868 E AndroidRuntime: 	at ai.mlc.mlcllm.BackgroundWorker$start$1.invoke(MLCEngine.kt:18)
08-08 14:44:55.609 15833 15868 E AndroidRuntime: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): Android
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): MacOS
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...) Android Redmi K70, XiaoMi 13
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source): source
 - Python version (e.g. 3.10): 3.11
 - GPU driver version (if applicable):
 - CUDA/cuDNN version (if applicable):
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):USE_NVTX: OFF
USE_GTEST: AUTO
SUMMARIZE: OFF
TVM_DEBUG_WITH_ABI_CHANGE: OFF
USE_IOS_RPC: OFF
USE_MSC: OFF
USE_ETHOSU: OFF
CUDA_VERSION: NOT-FOUND
USE_LIBBACKTRACE: AUTO
DLPACK_PATH: 3rdparty/dlpack/include
USE_TENSORRT_CODEGEN: OFF
USE_THRUST: OFF
USE_TARGET_ONNX: OFF
USE_AOT_EXECUTOR: ON
BUILD_DUMMY_LIBTVM: OFF
USE_CUDNN: OFF
USE_TENSORRT_RUNTIME: OFF
USE_ARM_COMPUTE_LIB_GRAPH_EXECUTOR: OFF
USE_CCACHE: AUTO
USE_ARM_COMPUTE_LIB: OFF
USE_CPP_RTVM: OFF
USE_OPENCL_GTEST: /path/to/opencl/gtest
TVM_LOG_BEFORE_THROW: OFF
USE_MKL: OFF
USE_PT_TVMDSOOP: OFF
MLIR_VERSION: NOT-FOUND
USE_CLML: OFF
USE_STACKVM_RUNTIME: OFF
USE_GRAPH_EXECUTOR_CUDA_GRAPH: OFF
ROCM_PATH: /opt/rocm
USE_DNNL: OFF
USE_MSCCL: OFF
USE_VITIS_AI: OFF
USE_MLIR: OFF
USE_RCCL: OFF
USE_LLVM: llvm-config --ignore-libllvm --link-static
USE_VERILATOR: OFF
USE_TF_TVMDSOOP: OFF
USE_THREADS: ON
USE_MSVC_MT: OFF
BACKTRACE_ON_SEGFAULT: OFF
USE_GRAPH_EXECUTOR: ON
USE_NCCL: OFF
USE_ROCBLAS: OFF
GIT_COMMIT_HASH: f5f048bbd71513f087799f987019e3931f68a6d9
USE_VULKAN: OFF
USE_RUST_EXT: OFF
USE_CUTLASS: OFF
USE_CPP_RPC: OFF
USE_HEXAGON: OFF
USE_CUSTOM_LOGGING: OFF
USE_UMA: OFF
USE_FALLBACK_STL_MAP: OFF
USE_SORT: ON
USE_RTTI: ON
GIT_COMMIT_TIME: 2024-06-03 09:18:53 -0400
USE_HEXAGON_SDK: /path/to/sdk
USE_BLAS: none
USE_ETHOSN: OFF
USE_LIBTORCH: OFF
USE_RANDOM: ON
USE_CUDA: OFF
USE_COREML: OFF
USE_AMX: OFF
BUILD_STATIC_RUNTIME: OFF
USE_CMSISNN: OFF
USE_KHRONOS_SPIRV: OFF
USE_CLML_GRAPH_EXECUTOR: OFF
USE_TFLITE: OFF
USE_HEXAGON_GTEST: /path/to/hexagon/gtest
PICOJSON_PATH: 3rdparty/picojson
USE_OPENCL_ENABLE_HOST_PTR: OFF
INSTALL_DEV: OFF
USE_PROFILER: ON
USE_NNPACK: OFF
LLVM_VERSION: 17.0.6
USE_MRVL: OFF
USE_OPENCL: OFF
COMPILER_RT_PATH: 3rdparty/compiler-rt
RANG_PATH: 3rdparty/rang/include
USE_SPIRV_KHR_INTEGER_DOT_PRODUCT: OFF
USE_OPENMP: none
USE_BNNS: OFF
USE_FLASHINFER: OFF
USE_CUBLAS: OFF
USE_METAL: ON
USE_MICRO_STANDALONE_RUNTIME: OFF
USE_HEXAGON_EXTERNAL_LIBS: OFF
USE_ALTERNATIVE_LINKER: AUTO
USE_BYODT_POSIT: OFF
USE_HEXAGON_RPC: OFF
USE_MICRO: OFF
DMLC_PATH: 3rdparty/dmlc-core/include
INDEX_DEFAULT_I64: ON
USE_RELAY_DEBUG: OFF
USE_RPC: ON
USE_TENSORFLOW_PATH: none
TVM_CLML_VERSION:
USE_MIOPEN: OFF
USE_ROCM: OFF
USE_PAPI: OFF
USE_CURAND: OFF
TVM_CXX_COMPILER_PATH: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
HIDE_PRIVATE_SYMBOLS: ON

 - Any other relevant information:
I tried the sample apk download from doc, and it didn't crash.

**Comment by psb-cc** [comment] 2024-08-13 06:04
I'm facing the same exact issue. But, interestingly, the error I encountered is the opposite of yours: `org.apache.tvm.Base$TVMError: InternalError: Check failed: type_code_ == kDLInt (8 vs. 0) : expected int but got Object`

**Comment by MasterJH5574** [comment] 2024-08-14 15:45
Cross linking https://github.com/mlc-ai/mlc-llm/issues/2797#issuecomment-2289141823, could you help check if the 3rdparty needs update? I am not able to reproduce this issue on my end.

**Comment by psb-cc** [comment] 2024-08-16 10:30
Hi @ccyina, try pulling the latest changes from the repo. It worked for me.

**Comment by ccyina** [comment] 2024-08-16 12:04
> Cross linking [#2797 (comment)](https://github.com/mlc-ai/mlc-llm/issues/2797#issuecomment-2289141823), could you help check if the 3rdparty needs update? I am not able to reproduce this issue on my end.

I tried resync 3rdparty/tvm and build it, but still crash....

08-16 19:30:52.050  9656   959 E AndroidRuntime: FATAL EXCEPTION: Thread-8
08-16 19:30:52.050  9656   959 E AndroidRuntime: Process: ai.mlc.mlcengineexample, PID: 9656
08-16 19:30:52.050  9656   959 E AndroidRuntime: org.apache.tvm.Base$TVMError: InternalError: Check failed: type_code_ == kTVMObjectHandle (0 vs. 8) : expected Object but got int
08-16 19:30:52.050  9656   959 E AndroidRuntime: Stack trace:
08-16 19:30:52.050  9656   959 E AndroidRuntime:   File "/Users/banma-1509/Develop/LLM/mlc-llm/android/mlc4j/../../3rdparty/tvm/include/tvm/runtime/packed_func.h", line 2080
08-16 19:30:52.050  9656   959 E AndroidRuntime:
08-16 19:30:52.050  9656   959 E AndroidRuntime: 	at org.apache.tvm.Base.checkCall(Base.java:173)
08-16 19:30:52.050  9656   959 E AndroidRuntime: 	at org.apache.tvm.Function.invoke(Function.java:130)
08-16 19:30:52.050  9656   959 E AndroidRuntime: 	at ai.mlc.mlcllm.JSONFFIEngine.runBackgroundLoop(JSONFFIEngine.java:64)
08-16 19:30:52.050  9656   959 E AndroidRuntime: 	at ai.mlc.mlcllm.MLCEngine$backgroundWorker$1.invoke(MLCEngine.kt:42)
08-16 19:30:52.050  9656   959 E AndroidRuntime: 	at ai.mlc.mlcllm.MLCEngine$backgroundWorker$1.invoke(MLCEngine.kt:40)
08-16 19:30:52.050  9656   959 E AndroidRuntime: 	at ai.mlc.mlcllm.BackgroundWorker$start$1.invoke(MLCEngine.kt:19)
08-16 19:30:52.050  9656   959 E AndroidRuntime: 	at ai.mlc.mlcllm.BackgroundWorker$start$1.invoke(MLCEngine.kt:18)
08-16 19:30:52.050  9656   959 E AndroidRuntime: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)


This is my change,  use bundle_weight for Qwen2-0.5B-Instruct-q4f16_1-MLC:

diff --git a/android/MLCEngineExample/app/src/main/java/ai/mlc/mlcengineexample/MainActivity.kt b/android/MLCEngineExample/app/src/main/java/ai/mlc/mlcengineexample/MainActivity.kt
index bb716610..25de27c2 100644
--- a/android/MLCEngineExample/app/src/main/java/ai/mlc/mlcengineexample/MainActivity.kt
+++ b/android/MLCEngineExample/app/src/main/java/ai/mlc/mlcengineexample/MainActivity.kt
@@ -29,11 +29,11 @@ class MainActivity : ComponentActivity() {
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)

-        val modelName = "phi-2-q4f16_1-MLC"
+        val modelName = "Qwen2-0.5B-Instruct-q4f16_1-MLC"
         var modelPath = File(application.getExternalFilesDir(""), modelName).toString()
         Log.i("MLC", "model path: $modelPath")
         // need to be changed to the custom system lib prefix used while compiling the model
-        val modelLib = "phi_msft_q4f16_1_686d8979c6ebf05d142d9081f1b87162"
+        val modelLib = "qwen2_q4f16_1_dbc9845947d563a3c13bf93ebf315c83"
         Log.i("MLC", "engine loaded")

         setContent {
diff --git a/android/MLCEngineExample/mlc-package-config.json b/android/MLCEngineExample/mlc-package-config.json
index 84d569f7..296f7d6f 100644
--- a/android/MLCEngineExample/mlc-package-config.json
+++ b/android/MLCEngineExample/mlc-package-config.json
@@ -2,12 +2,10 @@
     "device": "android",
     "model_list": [
         {
-            "model": "HF://mlc-ai/phi-2-q4f16_1-MLC",
-            "estimated_vram_bytes": 2036816936,
-            "model_id": "phi-2-q4f16_1-MLC",
-            "overrides": {
-                "prefill_chunk_size": 1024
-            }
+            "model": "HF://mlc-ai/Qwen2-0.5B-Instruct-q4f16_1-MLC",
+            "estimated_vram_bytes": 3980990464,
+            "model_id": "Qwen2-0.5B-Instruct-q4f16_1-MLC",
+            "bundle_weight": true
         }
     ]
 }


I build mlc_llm use source, and this is my config:
set(TVM_SOURCE_DIR 3rdparty/tvm)
set(CMAKE_BUILD_TYPE RelWithDebInfo)
set(USE_CUDA OFF)
set(USE_CUTLASS OFF)
set(USE_CUBLAS OFF)
set(USE_ROCM OFF)
set(USE_VULKAN OFF)
set(USE_METAL OFF)
set(USE_OPENCL OFF)
set(USE_OPENCL_ENABLE_HOST_PTR OFF)
set(USE_FLASHINFER OFF)

**Comment by Mawriyo** [comment] 2024-08-16 17:55
This still persists even after updated my modules as well.

**Comment by mengshyu** [comment] 2024-08-22 14:59
Hi @ccyina The current mechanism caches the previously compiled model library to reduce compilation time. However, if the runtime (TVM) is updated, it may cause APIs to become incompatible. This issue can be resolved by either exporting the environment variable MLC_JIT_POLICY=REDO or clearing all previously compiled libraries. The path to the libraries on Ubuntu is ~/.cache/mlc_llm/model_lib. After clearing the libraries, re-executing the mlc_llm package should fix the issue.

**Comment by ThangPM** [comment] 2024-08-24 17:42
When pulling the latest code, make sure you also pull the latest submodules such as tvm as well.

```
git submodule update --init --recursive
```

Otherwise, there will be a mismatch issue between mlc-llm and the tvm library. Then just follow what @mengshyu suggested then you should be good.

**Comment by ccyina** [comment] 2024-08-26 06:29
@mengshyu it works, i cleaned my macos mode lib cache (~/.cache/mlc_llm/model_lib).  Many thanks！

**Comment by ccyina** [comment] 2024-08-26 06:32
> Hi @ccyina The current mechanism caches the previously compiled model library to reduce compilation time. However, if the runtime (TVM) is updated, it may cause APIs to become incompatible. This issue can be resolved by either exporting the environment variable MLC_JIT_POLICY=REDO or clearing all previously compiled libraries. The path to the libraries on Ubuntu is ~/.cache/mlc_llm/model_lib. After clearing the libraries, re-executing the mlc_llm package should fix the issue.

@Mawriyo try this, it works for me

**Closed** 2024-08-26 06:46 UTC
Labels: bug

**Comment by ccyina** [comment] 2024-08-26 06:51
step:

1. resync project
git submodule update --init --recursive
2. clean cache 
rm -rf ~/.cache/mlc_llm/model_lib
3. rebuild project 
MLC_JIT_POLICY=REDO mlc_llm package

**Comment by Mawriyo** [comment] 2024-08-27 15:14
@ccyina The "rm -rf ~/.cache/mlc_llm/model_lib" would have likely resolved my issue... but my solution was to remove and recompiled my model libraries and that seemed to solve the trick. I believe the old models were packaged with a older version of MLC and as a result caused this error but your suggestion likely would have worked as well.

**Comment by Acoee** [comment] 2024-09-04 11:13
The solution all above, no one works for me💔
