### ISSUE TITLE
[Question][Android] Lower speed and GPU usage with SLM than legacy workflow on Android Adreno GPU

### ISSUE THREAD

**Issue by sbwww** [mlc-ai/mlc-llm#1896] opened 2024-03-06 08:16 UTC
## ❓ General Questions

I tried both workflows of `mlc_llm.build` (legacy) and `mlc_chat compile` (SLM) to compile and deploy Llama2 7B `q4f16_1` model on Qualcomm 8gen3 device.

With the same input (42 tokens prefilled), the decoding speed diverges between legacy and SLM. SLM is ~10% slower than legacy.

I profiled the GPU usage with https://kite.mi.com/ as follows. It seems that model compiled with SLM (~80%) has a lower GPU usage than legacy (~87%) at decoding stage.

|legacy|SLM|
|:-:|:-:|
|decode 425 tokens, 10.1 t/s|decode 254 tokens, 9.0 t/s|
|![image](https://github.com/mlc-ai/mlc-llm/assets/45259695/86a936a9-83e2-4ace-9f99-e0734cbeb83d)|![image](https://github.com/mlc-ai/mlc-llm/assets/45259695/f8a3346a-5e31-4672-bc1d-8c634272a789)|

Possibly related to
- https://github.com/mlc-ai/mlc-llm/issues/1723#issuecomment-1951409989
  slower decoding speed with SLM
- https://github.com/mlc-ai/mlc-llm/pull/1536
  enhaced Android implementation with legacy, but not yet integrated into SLM

I assume that #1536 contributes to the faster speed of legacy workflow. Haven't tested `q4f16_0` quantization yet.

**Comment by sbwww** [comment] 2024-03-06 09:04
> Haven't tested `q4f16_0` quantization yet.

Similar pattern found in `q4f16_0` quantization.

Notably, SLM barely reaches 6.5 token/s, and legacy is 11.5 token/s (prefill 42 tokens + decode 300 tokens)

**Comment by spectrometerHBH** [comment] 2024-03-09 16:50
https://github.com/mlc-ai/mlc-llm/pull/1915

**Comment by tqchen** [comment] 2024-03-11 16:46
The attention regression should be fixed by #1915 . In the meantime, given all the known gaps are ready, we will proceed with the deprecation, so followup steps can move forward @srkreddy1238 would be great if you can also help bring some of the `q4f16_0` optimizations to the new flow

**Closed** 2024-03-12 09:18 UTC
Labels: question

**Comment by tqchen** [comment] 2024-03-12 13:25
Thank you @sbwww for reporting and love to continue work together improving the new flow

**Comment by srkreddy1238** [comment] 2024-04-02 11:38
We find q4f16_0 being more convenient for Adreno (though we tried improving q4f16_1 initially). Now q4f16_0 compatible dlight schedules (GEMV, MatMul) are improved.
We fell shot of earlier performance with PagedAttn regressing. Let me give  a try with https://github.com/mlc-ai/mlc-llm/pull/1915.

I feel the heat with somany options here, will start giving out the internal optimizations for Adreno  soon

**Comment by tqchen** [comment] 2024-04-02 13:31
Love to see these land @srkreddy1238 ! i know there can be a slight setbacks due to migration, but hopefully the new engine would offer path towards more useful things like speculation and more
