### ISSUE TITLE
PHI 1.5 - Realistic model size with incredible performance

### ISSUE THREAD

**Issue by axel578** [mlc-ai/mlc-llm#998] opened 2023-09-30 12:45 UTC
## 🚀 Feature
To support microsoft phi 1.5 : https://huggingface.co/microsoft/phi-1_5
a big mistake would be to consider this as not important, like its completly made for small devices.

## Motivation

Small model size on small device is the way to go

## Alternatives

None

## Additional context

with 1.3 billion parameters (~GPT2) it should run at incredible speed on any small device , and since its benchmark as powerfull as certain 13B models, it is incredibly interesting to implement it for small devices !!

**Comment by niutech** [comment] 2023-12-18 21:18
Duplicate of #905.

**Closed** 2024-04-06 02:23 UTC
Labels: feature request
