### ISSUE TITLE
[Bug] Custom models compiled for WEBGPU in the latest version are invalid

### ISSUE THREAD

**Issue by arjunzo** [mlc-ai/mlc-llm#1951] opened 2024-03-13 14:18 UTC
## 
The model can be compiled without error, but when loading is completed, an error is reported in the browser, as shown below:
<img width="1033" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/88835295/fbfa693d-e8c8-47f2-b834-0e3a5666ffde">
After checking the source code, this is caused by the following call to the WebGPUDeviceAPI::GetCurrentStream function. I don’t know why. Please see the picture below:
<img width="735" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/88835295/17c47fe4-0f85-4f62-bee8-97fc286be84f">

Rolled back to 1 month ago and used "mlc-llm\mlc_llm2\build.py" to compile. As a result, no error was reported when loading. It may be that does not use Paged KVCache, but an error was reported during inference.
`python build.py --model ../../models/TinyLlama-1.1B-Chat-v0.4/  --target webgpu --quantization q4f32_1`

<img width="1193" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/88835295/99bf5fe6-72f8-4f71-a18e-ee180bbc3809">

How to download the old TVM Unity Compiler?

**Comment by MasterJH5574** [comment] 2024-03-13 15:03
Apologies for the issue. We should not call `GetCurrentStream` outside the `if` in PagedAttentionKVCache. Moving it inside the `if` can work I think. I will work on a fix soon.

**Comment by MasterJH5574** [comment] 2024-03-13 16:51
Submitted a fix here https://github.com/apache/tvm/pull/16714.

**Comment by arjunzo** [comment] 2024-03-13 22:33
Thank you @MasterJH5574 
If you modify it in the way given above, the "Not implemented" error will not be reported, but the following error will occur:
<img width="1054" alt="image" src="https://github.com/mlc-ai/mlc-llm/assets/88835295/1d7ce766-2298-424b-ba70-c0b385ceb602">

Is there any way to avoid this? Because the error is from Chrome, should it be avoided when compiling the model?

**Comment by MasterJH5574** [comment] 2024-03-14 01:32
Copy @CharlieFRuan on the WebGPU issue above -- did we confirm that all the kernels are within the limit?

**Comment by CharlieFRuan** [comment] 2024-03-14 02:49
Was able to reproduce. Looking at the dumped shader, the kernels that break the limit are: `apply_bitmask_inplace_kernel()`, `apply_penalty_inplace_kernel()`, `apply_logit_bias_inplace_kernel()`.

I think this is due to https://github.com/mlc-ai/mlc-llm/pull/1934, taking a look now.

**Comment by CharlieFRuan** [comment] 2024-03-14 05:02
Hi @arjunzo this PR should fix the kernel size issue: https://github.com/mlc-ai/mlc-llm/pull/1955

However, you may further run into issues complaining about the shape when calling `embed`. This is due to PR https://github.com/mlc-ai/mlc-llm/pull/1908, and how WebLLM has not updated its runtime to adapt to the change.

I will send another PR tomorrow in WebLLM to fix this. Meanwhile, for a temporary fix, you could simply look at https://github.com/mlc-ai/mlc-llm/pull/1908, and manually change
```python
"input_ids": nn.spec.Tensor(["seq_len"], "int32"),
```
back to
```python
"input_ids": nn.spec.Tensor([1, "seq_len"], "int32"),
```

**Comment by MasterJH5574** [comment] 2024-03-14 14:26
#1955 is merged. Apologies for the mistake 🙏

**Closed** 2024-03-16 12:18 UTC
Labels: bug
