### ISSUE TITLE
Response output truncated [Bug]

### ISSUE THREAD

**Issue by ali-libertify** [mlc-ai/mlc-llm#1060] opened 2023-10-13 11:48 UTC
## 🐛 Bug

Hello,
 I am getting truncated responses (generation stops mid-sentence) while using the mlc-llm rest api.

## To Reproduce

I am currently running llama 2 13b chat q8f16_1 on an A10G on huggingface and getting truncated responses when the prompt is about 2k tokens.

I am getting the following warning on the server side:

`Warning: The prompt tokens are more than `max_window_size`, the input will be truncated. `

I tried increasing the max_window_size in mlc-chat-config.json to 8k but I am still getting the issue.

## Expected behavior

Have complete responses from the llm.

## Environment

 - Platform (e.g. WebGPU/Vulkan/IOS/Android/CUDA): CUDA
 - Operating system (e.g. Ubuntu/Windows/MacOS/...): Ubuntu
 - Device (e.g. iPhone 12 Pro, PC+RTX 3090, ...): A10G
 - How you installed MLC-LLM (`conda`, source): source
 - How you installed TVM-Unity (`pip`, source):
 - Python version (e.g. 3.10): 3.9
 - GPU driver version (if applicable): 
 - CUDA/cuDNN version (if applicable): 11.8
 - TVM Unity Hash Tag (`python -c "import tvm; print('\n'.join(f'{k}: {v}' for k, v in tvm.support.libinfo().items()))"`, applicable if you compile models):

**Comment by junrushao** [comment] 2023-10-17 16:35
Right. When building the model lib, there’s an option “--max-seq-len” you may tweak, which by default, is 2048. You may refer to “Step 3” here to tweak this parameter: https://github.com/mlc-ai/llm-perf-bench#mlc-llm

**Comment by ali-libertify** [comment] 2023-10-23 10:03
@junrushao, I am getting an issue with the compiled model. The compilation is successful but when I try to get a completion I get the following error:

`
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/medal/Desktop/workspace/workspace_wsl/vllm/rest.py", line 208, in generate
    session["chat_mod"]._prefill(input=request.prompt)
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/mlc_chat/chat_module.py", line 980, in _prefill
    self._prefill_func(input, decode_next_token, place_in_prompt.value, generation_config_str)
  File "tvm/_ffi/_cython/./packed_func.pxi", line 332, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 277, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./base.pxi", line 182, in tvm._ffi._cy3.core.CHECK_CALL
  File "/home/ali/anaconda3/envs/mlc/lib/python3.11/site-packages/tvm/_ffi/base.py", line 476, in raise_last_ffi_error
    raise py_err
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1322, in mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 800, in mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String)
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 981, in mlc::llm::LLMChat::SampleTokenFromLogits(tvm::runtime::NDArray, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, picojson::value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, picojson::value> > >)
  File "/workspace/mlc-llm/cpp/llm_chat.cc", line 1108, in mlc::llm::LLMChat::Softmax(tvm::runtime::NDArray, tvm::runtime::NDArray)
ValueError: Traceback (most recent call last):
  10: mlc::llm::LLMChatModule::GetFunction(tvm::runtime::String const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#5}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const
        at /workspace/mlc-llm/cpp/llm_chat.cc:1322
  9: mlc::llm::LLMChat::PrefillStep(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, mlc::llm::PlaceInPrompt, tvm::runtime::String)
        at /workspace/mlc-llm/cpp/llm_chat.cc:800
  8: mlc::llm::LLMChat::SampleTokenFromLogits(tvm::runtime::NDArray, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, picojson::value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, picojson::value> > >)
        at /workspace/mlc-llm/cpp/llm_chat.cc:981
  7: mlc::llm::LLMChat::Softmax(tvm::runtime::NDArray, tvm::runtime::NDArray)
        at /workspace/mlc-llm/cpp/llm_chat.cc:1108
  6: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeClosurePacked(tvm::runtime::ObjectRef const&, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  5: tvm::runtime::PackedFuncObj::Extractor<tvm::runtime::PackedFuncSubObj<tvm::runtime::relax_vm::VirtualMachineImpl::GetClosureInternal(tvm::runtime::String const&, bool)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#1}> >::Call(tvm::runtime::PackedFuncObj const*, tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  4: tvm::runtime::relax_vm::VirtualMachineImpl::InvokeBytecode(long, std::vector<tvm::runtime::TVMRetValue, std::allocator<tvm::runtime::TVMRetValue> > const&)
  3: tvm::runtime::relax_vm::VirtualMachineImpl::RunLoop()
  2: tvm::runtime::relax_vm::VirtualMachineImpl::RunInstrCall(tvm::runtime::relax_vm::VMFrame*, tvm::runtime::relax_vm::Instruction)
  1: tvm::runtime::relax_vm::CheckTensorInfo(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)
  0: _ZN3tvm7runtime6deta
  File "/workspace/tvm/src/runtime/relax_vm/builtin.cc", line 177
ValueError: Check failed: (ptr->dl_tensor.ndim == ndim) is false: ErrorContext(fn=softmax_with_temperature, loc=param[1], param=temperature, annotation=R.Tensor((nseq,), dtype="float32"))  expect Tensor with ndim 1 but get 0
`

**Comment by junrushao** [comment] 2023-10-24 05:22
I believe this particular issue has been fixed by [this commit](https://github.com/mlc-ai/mlc-llm/commit/204860b786460247f77717053cd3a4e1e0069b06). See also [bug report](https://github.com/mlc-ai/mlc-llm/issues/1065) from last week

**Comment by junrushao** [comment] 2023-10-24 14:53
This is very strange because the prefill function indeed requires 4 inputs...

**Comment by junrushao** [comment] 2023-10-24 15:46
I am able to reproduce this issue. Digging

**Comment by junrushao** [comment] 2023-10-24 16:02
Fix #1120

**Comment by junrushao** [comment] 2023-10-24 16:15
I reverted this particular commit to temporarily unblock us from this issue, and now am rebuilding the nightly wheels. Will update here as soon as the wheels are updated (expect ~2h).

@Lunderberg I apologize for the temporary revert, please feel free to submit this commit again as long as it runs through the existing flow

**Comment by ali-libertify** [comment] 2023-10-24 16:16
Ok. Thanks!

**Comment by junrushao** [comment] 2023-10-24 18:40
The wheels have been updated. You may try again!

**Comment by Lunderberg** [comment] 2023-10-24 19:05
@junrushao I have a bugfix PR submitted [here](https://github.com/mlc-ai/mlc-llm/pull/1127).  The root cause was an extra `.without_attr("num_input")` in `ParamManager.transform_dequantize`.  I was able to reproduce the bug with the earlier implementation, and to verify that it is resolved with the updated PR.

**Comment by MasterJH5574** [comment] 2023-10-30 19:10
thanks everyone, glad it get fixed, closing for now. feel free to open  new issues

**Closed by MasterJH5574** 2023-10-30 19:10 UTC
Labels: bug
